app: apihydra
kind: steps
metadata:
  name: config-03-post
spec:
  steps:
  - request:
      method: POST
      path: /api/v1/project/delete
      body: '{"id":${config_project}}'
    response:
      expected_status: 204
  - request:
      method: POST
      path: /api/v1/project/details
      body: '{"id":${config_project}}'
    response:
      expected_status: 404
