drop function if exists public.fn_change_insert;
drop function if exists public.fn_change_start_run;
drop function if exists public.fn_change_reset_claim;
drop function if exists public.fn_change_update_run;
drop procedure if exists public.sp_change_assign_flow;
drop procedure if exists public.sp_change_ref_update;
drop procedure if exists public.sp_change_phase_update;
drop procedure if exists public.sp_change_title_update;
drop procedure if exists public.sp_change_idea_update;
drop procedure if exists public.sp_change_def_update;
drop procedure if exists public.sp_change_brief_update;
drop procedure if exists public.sp_change_spec_update;
drop procedure if exists public.sp_change_pr_update;
drop procedure if exists public.sp_change_ref;
drop procedure if exists public.sp_epic_to_history;
drop procedure if exists public.sp_change_to_history;
drop procedure if exists public.sp_requirement_to_history;
drop procedure if exists public.sp_change_requirement_recalculate;
drop procedure if exists public.sp_epic_requirement_recalculate;
drop function if exists public.fn_testcase_insert;
drop procedure if exists public.sp_testcase_insert;
drop procedure if exists public.sp_testcase_update;
drop procedure if exists public.sp_testcase_update_scenario;
drop procedure if exists public.sp_testcase_update_done;
drop procedure if exists public.sp_testcase_update_change;
drop procedure if exists public.sp_testcase_delete;
drop procedure if exists public.sp_testcase_to_history;
drop procedure if exists public.sp_epic_testcase_recalculate;
drop procedure if exists public.sp_change_testcase_recalculate;
drop function if exists public.fn_change_testcase_recalculate;
drop function if exists public.fn_testcase_update_scenario;
drop function if exists public.fn_testcase_history_insert;
drop procedure if exists public.sp_change_tc_count_recalculate;
drop function if exists public.fn_testcase_delete(bigint, smallint);
drop function if exists public.fn_testcase_delete(bigint, integer);

drop view if exists public.vw_foreign_key;
drop view if exists public.vw_project;
drop view if exists public.vw_project_list;
drop view if exists public.vw_epic;
drop view if exists public.vw_epic_list;
drop view if exists public.vw_epic_inactive_list;
drop view if exists public.vw_change;
drop view if exists public.vw_change_list;
drop view if exists public.vw_change_inactive_list;
drop view if exists public.vw_change_details;
drop view if exists public.vw_doc_active;

drop table if exists public.doc_active cascade;
drop table if exists public.doc cascade;
drop table if exists public.requirement_history cascade;
drop table if exists public.requirement cascade;
drop table if exists public.testcase;
drop table if exists public.testcase_history;
drop table if exists public.change_history cascade;
drop table if exists public.change cascade;
drop table if exists public.change_phase cascade;
drop table if exists public.change_type cascade;
drop table if exists public.epic_history cascade;
drop table if exists public.epic cascade;
drop table if exists public.project cascade;
drop table if exists public.config cascade;

-- project.config_slug references config (slug)
-- <all>.created_by references user (id) - fk purposely omitted
-- <all>.updated_by references user (id) - fk purposely omitted
-- Intentional: API project_id is immutable; backend validation enforces same-project epic assignment.
-- Composite FK deliberately omitted; flag validation bypasses, not the absent FK or supporting UNIQUE.

create table public.config
(
    slug          text                     default 'default'::text primary key not null,
    project_docs  text[]                                                       not null,
    epic_docs     text[]                                                       not null,
    change_docs   text[]                                                       not null,
    change_phases text[]                                                       not null,
    change_colors text[]                                                       not null,
    change_types  text[]                                                       not null,
    created_by    bigint                   default 0                           not null,
    updated_by    bigint                   default 0                           not null,
    created_at    timestamp with time zone default now()                       not null,
    updated_at    timestamp with time zone default now()                       not null
);

create table public.project
(
    id          bigint generated by default as identity primary key not null,
    name        text                                                not null,
    config_slug text                     default 'default'          not null references public.config (slug),
    last_ref    integer                  default 0                  not null,
    active      bool                     default true               not null,
    created_by  bigint                   default 0                  not null,
    updated_by  bigint                   default 0                  not null,
    created_at  timestamp with time zone default now()              not null,
    updated_at  timestamp with time zone default now()              not null
);

create table public.epic
(
    id         bigint generated by default as identity primary key not null,
    project_id bigint                                              not null references public.project (id),
    name       text                                                not null,
    active     bool                     default true               not null,
    created_by bigint                   default 0                  not null,
    updated_by bigint                   default 0                  not null,
    created_at timestamp with time zone default now()              not null,
    updated_at timestamp with time zone default now()              not null
);

create index epic_project_id_idx
    on public.epic (project_id);

--     done_tc      integer                  default 0                 not null,
--     total_tc     integer                  default 0                 not null,
--     completed    integer generated always as (COALESCE(
--             ((((100 * done_tc) / NULLIF(total_tc, 0))) ::int)::int, 0)) stored,

create table public.change
(
    id              bigint generated by default as identity primary key,
    ref_uuid        uuid                     default gen_random_uuid() not null,
    ref             integer,
    slug            text,
    project_id      bigint                                             not null references public.project (id),
    epic_id         bigint references public.epic (id),
    after_change_id bigint references public.change (id),
    change_phase    text                     default 'backlog'::text   not null,
    change_types    text[]                   default ARRAY []::text[]  not null,
    title           text                     default ''::text          not null,
    pr_url          text                     default ''::text          not null,
    active          boolean                  default true              not null,
    created_by      bigint                   default 0                 not null,
    updated_by      bigint                   default 0                 not null,
    created_at      timestamp with time zone default now()             not null,
    updated_at      timestamp with time zone default now()             not null
);

create unique index change_ref_uuid_idx
    on public.change (ref_uuid);

create index change_project_id_idx
    on public.change (project_id);

create index change_epic_id_idx
    on public.change (epic_id);

-- doc table is used as append only - updated_by is added for consistency - it has no purpose
drop table if exists public.doc;
create table public.doc
(
    id         bigint generated by default as identity primary key,
    ref_table  text                                   not null,
    ref_id     bigint                                 not null,
    doc_type   text                                   not null,
    body       text                                   not null,
    agent_edit boolean                  default false not null,
    created_by bigint                   default 0     not null,
    updated_by bigint                   default 0     not null,
    deleted_by bigint,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    deleted_at timestamp with time zone
);

create index doc_ref_id_table_idx
    on public.doc (ref_table, ref_id);

drop table if exists public.doc_active;
create table public.doc_active
(
    ref_table text   not null,
    ref_id    bigint not null,
    doc_type  text   not null,
    doc_id    bigint not null references public.doc (id),
    primary key (ref_table, ref_id, doc_type)
);

create index doc_active_doc_id_idx
    on public.doc_active (doc_id);

drop table if exists public.test_case;
drop table if exists public.testcase;
create table public.testcase
(
    id         bigint generated by default as identity primary key,
    change_id  bigint                                 not null references public.change (id),
    scenario   text                                   not null,
    done       boolean                  default false not null,
    created_by bigint                   default 0     not null,
    updated_by bigint                   default 0     not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

create index testcase_change_id_idx
    on public.testcase (change_id);

create index testcase_change_id_done_idx
    on public.testcase (change_id, done);

drop table if exists public.user;
create table public.user
(
    id         bigint generated by default as identity primary key,
    email      text                                   not null,
    name       text                                   not null,
    token      text,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

--- views ---

create view public.vw_project_list as
SELECT p.id,
       p.name,
       (select count(*) from change c where c.project_id = p.id) AS change_count,
       p.active,
       p.created_by,
       p.updated_by,
       p.created_at,
       p.updated_at
FROM project p
ORDER BY p.active desc, p.updated_at desc;

create view public.vw_epic_list as
SELECT e.id,
       e.project_id,
       e.name,
       (select count(*)
        from change c
                 join testcase tc on tc.change_id = c.id and tc.done = true
        where c.epic_id = e.id)                               as done_tc,
       (select count(*)
        from change c
                 join testcase tc on tc.change_id = c.id
        where c.epic_id = e.id)                               as total_tc,
       (select count(*) from change c where c.epic_id = e.id) AS change_count,
       e.active,
       e.created_by,
       e.updated_by,
       e.created_at,
       e.updated_at
FROM epic e
ORDER BY e.project_id, e.name;

create view public.vw_change_list as
SELECT c.id,
       c.ref_uuid,
       (case when c.ref > 99 then c.ref::text else lpad(c.ref::text, 3, '0') end) || '-' || c.slug as ref_slug,
       c.project_id,
       c.change_phase,
       c.change_types,
       c.epic_id,
       e.name || ' (#' || c.epic_id || ')'                                                         AS epic_name,
       c.title,
       (select count(*) from testcase tc where tc.change_id = c.id and tc.done = true)             as done_tc,
       (select count(*) from testcase tc where tc.change_id = c.id)                                as total_tc,
       c.active,
       c.updated_at
FROM change c
         LEFT JOIN epic e ON c.epic_id = e.id
ORDER BY c.project_id, c.updated_at DESC;

create view public.vw_change_details as
SELECT c.id,
       c.ref_uuid,
       (case when c.ref > 99 then c.ref::text else lpad(c.ref::text, 3, '0') end) || '-' || c.slug as ref_slug,
       c.project_id,
       c.change_phase,
       c.change_types,
       c.epic_id,
       e.name                                                                                      AS epic_name,
       c.title,
       c.pr_url,
       c.after_change_id,
       ca.title || ' (#' || c.after_change_id::text || ')'                                         as after_change_name,
       c.active,
       (select count(*) from testcase tc where tc.change_id = c.id and tc.done = true)             as done_tc,
       (select count(*) from testcase tc where tc.change_id = c.id)                                as total_tc,
       c.created_by,
       c.updated_by,
       c.created_at,
       c.updated_at
FROM change c
         LEFT JOIN epic e ON c.epic_id = e.id
         LEFT JOIN change ca ON c.after_change_id = ca.id
ORDER BY c.project_id, c.updated_at DESC;

create view public.vw_doc_active as
select a.ref_table,
       a.ref_id,
       a.doc_type,
       a.doc_id,
       d.body,
       d.agent_edit,
       d.created_at,
       d.created_by,
       d.updated_at,
       d.updated_by,
       d.deleted_at,
       d.deleted_by
from doc_active a
         left join doc d on a.doc_id = d.id;

create view public.vw_foreign_key as
SELECT conname             AS foreign_key_name,
       conrelid::regclass  AS table_name,
       confrelid::regclass AS referenced_table
FROM pg_constraint
WHERE contype = 'f'::"char"
  AND connamespace = 'public'::regnamespace::oid
ORDER BY (conrelid::regclass), conname;

--- change ---

create function public.fn_change_insert(_project_id bigint, _ref_uuid uuid, _title text, _brief text) returns bigint
    language plpgsql
as
$$
declare
    _id         bigint;
    _updated_at timestamptz;
begin
    insert into public.change (project_id, ref_uuid, title)
    values ((select id from project where id = _project_id), _ref_uuid, _title)
    returning id, updated_at
        into _id, _updated_at;

    perform fn_doc_insert('change', _id, 'brief', _brief, false);

    return _id;
end;
$$;

drop procedure if exists public.sp_change_phase_update;
create procedure public.sp_change_phase_update(_change_id bigint, _phase text)
    language plpgsql
as
$$
begin
    update public.change
    set change_phase=_phase,
        updated_at=now()
    where id = _change_id;
end;
$$;

drop procedure if exists public.sp_change_epic_update;
create or replace procedure public.sp_change_epic_update(_id bigint, _epic_id bigint)
    language plpgsql
as
$$
begin
    update public.change
    set epic_id=_epic_id,
        updated_at=now()
    where id = _id;
end;
$$;

create procedure public.sp_change_title_update(_change_id bigint, _title text)
    language plpgsql
as
$$
begin
    update public.change
    set title=trim(regexp_replace(_title, '\s+', ' ', 'g')),
        updated_at=now()
    where id = _change_id;
end;
$$;

drop procedure if exists public.sp_change_slug_update;
create procedure public.sp_change_slug_update(_change_id bigint, _slug text)
    language plpgsql
as
$$
begin
    update public.change
    set slug=_slug,
        updated_at=now()
    where id = _change_id;
end;
$$;

create or replace procedure public.sp_doc_active_set(_ref_table text, _ref_id bigint, _doc_type text, _doc_id bigint)
    language plpgsql as
$$
begin
    insert into public.doc_active (ref_table, ref_id, doc_type, doc_id)
    values (_ref_table, _ref_id, _doc_type, _doc_id)
    on conflict (ref_table, ref_id, doc_type) do update set doc_id=_doc_id;

    update public.doc set updated_by=0, updated_at=now(), deleted_by=null, deleted_at=null
    where id=_doc_id and deleted_by is not null;
end;
$$;

create or replace function public.fn_doc_insert(_ref_table text, _ref_id bigint, _doc_type text, _body text, _agent_edit bool)
    returns bigint
    language plpgsql as
$$
declare
    _doc_id bigint;
begin
    insert into public.doc(ref_id, ref_table, doc_type, body, agent_edit)
    values (_ref_id, _ref_table, _doc_type, _body, _agent_edit)
    returning id into _doc_id;

    call sp_doc_active_set(_ref_table, _ref_id, _doc_type, _doc_id);

    return _doc_id;
end;
$$;

create or replace function public.fn_doc_comment_insert(_ref_id bigint, _ref_table text, _body text, _agent_edit bool)
    returns bigint
    language plpgsql as
$$
declare
    _id bigint;
begin
    insert into public.doc(ref_id, ref_table, doc_type, body, agent_edit)
    values (_ref_id, _ref_table, 'comment', _body, _agent_edit)
    returning id into _id;
    return _id;
end;
$$;

create or replace function public.fn_doc_comment_update(_id bigint, _body text)
    returns bigint
    language plpgsql as
$$
begin
    update public.doc
    set body=_body,
        updated_by=0,
        updated_at=now()
    where id = _id
      and doc_type = 'comment'
    returning id into _id;
    return _id;
end;
$$;

create or replace function public.fn_doc_delete(_id bigint)
    returns bigint
    language plpgsql as
$$
begin
    update public.doc
    set deleted_by=0,
        deleted_at=now()
    where id = _id
    returning id into _id;

    delete from public.doc_active where doc_id = _id;

    return _id;
end;
$$;
