drop function if exists public.fn_change_insert;
drop function if exists public.fn_change_start_run;
drop function if exists public.fn_change_reset_claim;
drop function if exists public.fn_change_update_run;
drop procedure if exists public.sp_change_assign_flow;
drop procedure if exists public.sp_change_ref_update;
drop procedure if exists public.sp_change_phase_update;
drop procedure if exists public.sp_change_title_update;
drop procedure if exists public.sp_change_idea_update;
drop procedure if exists public.sp_change_def_update;
drop procedure if exists public.sp_change_brief_update;
drop procedure if exists public.sp_change_spec_update;
drop procedure if exists public.sp_change_pr_update;
drop procedure if exists public.sp_change_ref;
drop procedure if exists public.sp_epic_to_history;
drop procedure if exists public.sp_change_to_history;
drop procedure if exists public.sp_requirement_to_history;
drop procedure if exists public.sp_change_requirement_recalculate;
drop procedure if exists public.sp_epic_requirement_recalculate;
drop function if exists public.fn_testcase_insert;
drop procedure if exists public.sp_testcase_insert;
drop procedure if exists public.sp_testcase_update;
drop procedure if exists public.sp_testcase_update_scenario;
drop procedure if exists public.sp_testcase_update_done;
drop procedure if exists public.sp_testcase_update_change;
drop procedure if exists public.sp_testcase_delete;
drop procedure if exists public.sp_testcase_to_history;
drop procedure if exists public.sp_epic_testcase_recalculate;
drop procedure if exists public.sp_change_testcase_recalculate;
drop function if exists public.fn_change_testcase_recalculate;
drop function if exists public.fn_testcase_update_scenario;
drop function if exists public.fn_testcase_history_insert;
drop procedure if exists public.sp_change_tc_count_recalculate;
drop function if exists public.fn_testcase_delete(bigint, smallint);
drop function if exists public.fn_testcase_delete(bigint, integer);

drop view if exists public.vw_foreign_key;
drop view if exists public.vw_project;
drop view if exists public.vw_epic;
drop view if exists public.vw_change;
drop view if exists public.vw_change_list;
drop view if exists public.vw_change_details;

drop table if exists public.requirement_history cascade;
drop table if exists public.requirement cascade;
drop table if exists public.testcase;
drop table if exists public.testcase_history;
drop table if exists public.change_history cascade;
drop table if exists public.change cascade;
drop table if exists public.change_phase cascade;
drop table if exists public.change_type cascade;
drop table if exists public.epic_history cascade;
drop table if exists public.epic cascade;
drop table if exists public.project cascade;
drop table if exists public.config cascade;

create table public.config
(
    slug          text                     default 'default'::text primary key not null,
    project_docs  text[]                                                       not null,
    epic_docs     text[]                                                       not null,
    change_docs   text[]                                                       not null,
    change_phases text[]                                                       not null,
    change_colors text[]                                                       not null,
    change_types  text[]                                                       not null,
    created       timestamp with time zone default now()                       not null,
    modified      timestamp with time zone default now()                       not null
);

create table public.project
(
    id       bigint generated by default as identity primary key not null,
    name     text                                                not null,
--  references config (slug) - fk purposely omitted
    config   text                     default 'default'          not null,
    last_ref integer                  default 0                  not null,
    created  timestamp with time zone default now()              not null,
    modified timestamp with time zone default now()              not null
);

create table public.epic
(
    id         bigint generated by default as identity primary key not null,
    project_id bigint                                              not null references public.project (id),
    name       text                                                not null,
    created    timestamp with time zone default now()              not null,
    modified   timestamp with time zone default now()              not null,
    unique (project_id, id)
);

--     done_tc      integer                  default 0                 not null,
--     total_tc     integer                  default 0                 not null,
--     completed    integer generated always as (COALESCE(
--             ((((100 * done_tc) / NULLIF(total_tc, 0))) ::int)::int, 0)) stored,

create table public.change
(
    id           bigint generated by default as identity primary key,
    ref_uuid     uuid                     default gen_random_uuid() not null,
    ref          integer,
    slug         text,
    project_id   bigint                                             not null references public.project (id),
    epic_id      bigint references epic (id),
    change_phase text                     default 'backlog'::text   not null,
    change_types text[]                   default ARRAY []::text[]  not null,
    title        text                     default ''::text          not null,
    pr_url       text                     default ''::text          not null,
    open         boolean                  default true              not null,
    created      timestamp with time zone default now()             not null,
    modified     timestamp with time zone default now()             not null
--    foreign key (project_id, epic_id) references public.epic (project_id, id) purposely omitted
);

create unique index change_ref_uuid_idx
    on public.change (ref_uuid);

create index change_project_id_idx
    on public.change (project_id);

create index change_epic_id_idx
    on public.change (epic_id);

-- doc table is used as append only
drop table if exists public.doc;
create table public.doc
(
    id         bigint generated by default as identity primary key,
    ref_id     bigint                                 not null,
    ref_table  text                                   not null,
    doc_type   text                                   not null,
    body       text                                   not null,
    agent_edit boolean                  default false not null,
    current    boolean                  default true  not null,
    created    timestamp with time zone default now() not null
);

create index doc_ref_id_table_idx
    on public.doc (ref_id, ref_table);

create index doc_ref_id_table_type_current_idx
    on public.doc (ref_id, ref_table, doc_type, current);

create table public.testcase
(
    id        bigint generated by default as identity primary key,
    change_id bigint                                 not null references public.change (id),
    scenario  text                                   not null,
    done      boolean                  default false not null,
    created   timestamp with time zone default now() not null,
    modified  timestamp with time zone default now() not null
);

create index testcase_change_id_idx
    on public.testcase (change_id);

create index testcase_change_id_done_idx
    on public.testcase (change_id, done);

--- views ---

create view public.vw_project as
SELECT p.id,
       p.name,
       (select count(*) from change c where c.project_id = p.id) AS change_count,
       p.created,
       p.modified
FROM project p
ORDER BY p.modified desc;

create view public.vw_epic as
SELECT e.id,
       e.project_id,
       e.name,
       (select count(*)
        from change c
                 join testcase tc on tc.change_id = c.id and tc.done = true
        where c.epic_id = e.id)                               as done_tc,
       (select count(*)
        from change c
                 join testcase tc on tc.change_id = c.id
        where c.epic_id = e.id)                               as total_tc,
       (select count(*) from change c where c.epic_id = e.id) AS change_count,
       e.created,
       e.modified
FROM epic e
ORDER BY e.project_id, e.name;

create view public.vw_change_list as
SELECT c.id,
       c.ref_uuid,
       c.ref,
       c.slug,
       c.project_id,
       c.change_phase,
       c.change_types,
       c.epic_id,
       e.name                                                                          AS epic_name,
       c.title,
       c.open,
       (select count(*) from testcase tc where tc.change_id = c.id and tc.done = true) as done_tc,
       (select count(*) from testcase tc where tc.change_id = c.id)                    as total_tc,
       c.modified
FROM change c
         LEFT JOIN epic e ON c.epic_id = e.id
ORDER BY c.project_id, c.modified DESC;

create view public.vw_change_details as
SELECT c.id,
       c.ref_uuid,
       c.ref,
       c.slug,
       c.project_id,
       c.change_phase,
       c.change_types,
       c.epic_id,
       e.name                                                                          AS epic_name,
       c.title,
       c.pr_url,
       c.open,
       (select count(*) from testcase tc where tc.change_id = c.id and tc.done = true) as done_tc,
       (select count(*) from testcase tc where tc.change_id = c.id)                    as total_tc,
       c.created,
       c.modified
FROM change c
         LEFT JOIN epic e ON c.epic_id = e.id
ORDER BY c.project_id, c.modified DESC;

create view public.vw_foreign_key as
SELECT conname             AS foreign_key_name,
       conrelid::regclass  AS table_name,
       confrelid::regclass AS referenced_table
FROM pg_constraint
WHERE contype = 'f'::"char"
  AND connamespace = 'public'::regnamespace::oid
ORDER BY (conrelid::regclass), conname;

--- change ---

create function public.fn_change_insert(_project_id bigint, _ref_uuid uuid, _title text, _brief text) returns bigint
    language plpgsql
as
$$
declare
    _id       bigint;
    _modified timestamptz;
begin
    insert into public.change (project_id, ref_uuid, title)
    values ((select id from project where id = _project_id), _ref_uuid, _title)
    returning id, modified
        into _id, _modified;

    insert into public.doc (ref_id, ref_table, doc_type, body, created)
    values (_id, 'change', 'brief', _brief, _modified);

    return _id;
end;
$$;

drop procedure if exists public.sp_change_phase_update;
create procedure public.sp_change_phase_update(_change_id bigint, _phase text)
    language plpgsql
as
$$
begin
    update public.change
    set change_phase=_phase,
        modified=now()
    where id = _change_id;
end;
$$;

drop procedure if exists public.sp_change_epic_update;
create or replace procedure public.sp_change_epic_update(_id bigint, _epic_id bigint)
    language plpgsql
as
$$
begin
    update public.change
    set epic_id=_epic_id,
        modified=now()
    where id = _id;
end;
$$;

create procedure public.sp_change_title_update(_change_id bigint, _title text)
    language plpgsql
as
$$
begin
    update public.change
    set title=trim(regexp_replace(_title, '\s+', ' ', 'g')),
        modified=now()
    where id = _change_id;
end;
$$;

drop procedure if exists public.sp_project_doc_set;
create procedure public.sp_project_doc_set(_project_id bigint, _doc_type text, _body text, _agent_edit bool)
    language plpgsql
as
$$
begin
    update public.project
    set modified=now()
    where id=_project_id;

    if not found then
        return;
    end if;

    update public.doc set current=false where ref_id=_project_id and ref_table='project' and doc_type=_doc_type and current=true;

    insert into public.doc (ref_id, ref_table, doc_type, body, agent_edit)
    values (_project_id, 'project', _doc_type, _body, _agent_edit);
end;
$$;

drop procedure if exists public.sp_epic_doc_set;
create procedure public.sp_epic_doc_set(_epic_id bigint, _doc_type text, _body text, _agent_edit bool)
    language plpgsql
as
$$
begin
    update public.epic
    set modified=now()
    where id=_epic_id;

    if not found then
        return;
    end if;

    update public.doc set current=false where ref_id=_epic_id and ref_table='epic' and doc_type=_doc_type and current=true;

    insert into public.doc (ref_id, ref_table, doc_type, body, agent_edit)
    values (_epic_id, 'epic', _doc_type, _body, _agent_edit);
end;
$$;

drop procedure if exists public.sp_change_doc_set;
create procedure public.sp_change_doc_set(_change_id bigint, _doc_type text, _body text, _agent_edit bool)
    language plpgsql
as
$$
begin
    update public.change
    set modified=now()
    where id=_change_id;

    if not found then
        return;
    end if;

    update public.doc set current=false where ref_id=_change_id and ref_table='change' and doc_type=_doc_type and current=true;

    insert into public.doc (ref_id, ref_table, doc_type, body, agent_edit)
    values (_change_id, 'change', _doc_type, _body, _agent_edit);
end;
$$;
